### ISSUE TITLE
How to scrap ALL album pages? As of today, there are 1875 pages

### ISSUE THREAD

**Issue by xdebbie** [nabaskes/Pitchforker#2]
Great script btw, but I have been trying to scrap all the albums available on pitchfork (around 33,700 albums according to my calculations). I am a complete beginner in Python so I am having issues understanding and modifying the script...
The script currently uses 

```
if __name__ == "__main__":
    default_link = 'https://pitchfork.com/best/high-scoring-albums/?page='
```

I would like to scrap all pages, from ?page=1 to ?page=1875, so I changed it to this

```
if __name__ == "__main__":
    default_link = 'https://pitchfork.com/reviews/albums/?page='
```

But it does not parse all pages, I am missing something here, perhaps a loop to crawl from page 1 to page 1,875. Any ideas on how could I do that?

I am also not really sure how I could adapt the RECURSION_DEPTH and MAX_WORKERS to achieve what I want.

Thank you!

**Comment by nabaskes** [comment]
Hi @xdebbie , I'm assuming you closing the issue means you figured this out?  Glad to see that somebody found this useful

**Comment by xdebbie** [comment]
Hi @nabaskes, cool stuff here! Yes, I ended up figuring it out after giving Python and peewee's documentations a nice read! I found that I just had to be more patient waiting for the script to run - it took a while... I figured that if I change the ```RECURSION_DEPTH```to 1 it avoids the duplicates and changing ```MAX_WORKERS```to 70 made the script run in an acceptable speed...

I'm a super beginner in Python and I've just started to learn (I'm actually learning front-end web dev but at some point I need to know more about databases). I've been playing with Beautiful Soup, Scrapy and peewee and found peewee a bit easier to understand.

I'm working on my school project at the moment - would you mind adding a license to this repo? I will include you in the citation file of my school project too, of course. Cheers!

**Comment by nabaskes** [comment]
Sweet, I've added the license - feel free to use this or any of my other public code in your projects.

Re the recursion depth and max_workers, I think those are probably dependent on the specific machine you're using, site you're scraping, etc - there's not much to do except tweak them.  Looking back, I think this would probably run better if it used `asyncio` instead, although not sure.  

Regardless, glad I could help, and I hope you have fun exploring into backend code and databases, since at least for me that's the most interesting part of development :)

**Comment by xdebbie** [comment]
Thank you! Just took some read on this `asyncio` [here](https://realpython.com/async-io-python/), it seems quite interesting... but a bit of a learning curve to me, but nice to have it in mind to try it out some time! 

Aha yea I'm definitely a front-end kind of girl but databases are quite some fun to learn! Let's see how far I get, still a lot to go lol

**Comment by nabaskes** [comment]
Definite agree from me!

Anyway, let me know you if need other help with this or any of my other repos
